---
deployment:
    tasks:
        # manual tasks are:
        # - create a subdomain tg-bot
        # - node setup: make sure the app uses the subdomain without any path
        # - node setup: maybe manually restart the app
        # - telegram: maybe manually set the webhook to https://tg-bot.<domain.com>/<bot-token>
        - export DEPLOYPATH=/home/gebeyama/gebeya-manager-bot/
        - /bin/cp -R bot $DEPLOYPATH
        - /bin/cp package.json $DEPLOYPATH
